### ISSUE TITLE
bugs in notebooks 

### ISSUE THREAD

**Issue by RolfHut** [eWaterCycle/streamingDataAssimilation#2]
when running Lorenz Model EnKF example-distributed.ipnyb I get this error:
`ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:numpy.core.multiarray._reconstruct'
  in "settings.yaml", line 5, column 13`

**Comment by Peter9192** [comment]
I got the same error in the "Lorenz 96 model ensemble demonstration.ipynb". Seems similar to [this issue](https://github.com/yaml/pyyaml/issues/266#issue-421060310). Changing 
`settings = yaml.safe_load(stream)` 
to 
`settings = yaml.load(stream, Loader=yaml.Loader)` in BMILorenz.py solved the issue for me.
